import { theme } from "./theme";

export const s = {
  page: { minHeight: "100vh", background: theme.bg, display: "flex", flexDirection: "column" },
  container: { maxWidth: 980, margin: "0 auto", width: "100%", padding: "24px 20px", flex: 1 },
  card: {
    background: theme.card,
    borderRadius: theme.radius,
    border: `1px solid ${theme.border}`,
    boxShadow: theme.shadow,
    padding: 22,
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 9,
    border: `1px solid ${theme.border}`,
    fontSize: 14,
    outline: "none",
    background: "#fff",
    color: theme.text,
    boxSizing: "border-box",
  },
  label: { fontSize: 12.5, fontWeight: 600, color: theme.textMuted, marginBottom: 5, display: "block" },
  btnPrimary: {
    background: theme.primary,
    color: "#fff",
    border: "none",
    borderRadius: 9,
    padding: "10px 18px",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
  },
  btnPurple: {
    background: theme.purple,
    color: "#fff",
    border: "none",
    borderRadius: 9,
    padding: "10px 18px",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
  },
  btnOutline: {
    background: "#fff",
    color: theme.primary,
    border: `1px solid ${theme.primary}`,
    borderRadius: 9,
    padding: "9px 16px",
    fontWeight: 600,
    fontSize: 13.5,
    cursor: "pointer",
  },
  btnDanger: {
    background: "#fff",
    color: theme.red,
    border: `1px solid ${theme.red}`,
    borderRadius: 9,
    padding: "9px 16px",
    fontWeight: 600,
    fontSize: 13.5,
    cursor: "pointer",
  },
  h1: { fontSize: 22, fontWeight: 800, color: theme.text, margin: "0 0 4px 0" },
  h2: { fontSize: 17, fontWeight: 700, color: theme.text, margin: "0 0 12px 0" },
  muted: { color: theme.textMuted, fontSize: 13 },
  error: {
    background: theme.redBg,
    color: theme.red,
    padding: "10px 14px",
    borderRadius: 9,
    fontSize: 13.5,
    marginBottom: 14,
  },
  success: {
    background: theme.greenBg,
    color: theme.green,
    padding: "10px 14px",
    borderRadius: 9,
    fontSize: 13.5,
    marginBottom: 14,
  },
};
